version: 2.1

gopath-param: &gopath-param
  gopath:
    description: |
      The $GOPATH value.
    type: string
    default: "/go"

commands:
  write-go-version-file:
    description: |
      Writes a file at the location "<< parameters.gopath >>/circleci/goversion" that contains the version of Go that
      should be used by commands. If a non-empty version is specified using the "go-version" parameter, that value is
      used. Otherwise, the content of the file at .palantir/go-version or /usr/local/go/VERSION is used. If no parameter
      is specified and none of these files exist, the command fails with an error.
    parameters:
      go-version:
        description: |
          If non-empty, this value is written as the Go version (files in the repository/image are not consulted). The
          version should be of the form specified in a Go distribution's VERSION file (for example, "go1.16.5").
        type: string
        default: ""
      <<: *gopath-param
    steps:
      - run:
          name: Writing go version to use in CircleCI job
          command: |
            # this pattern is used to make it easier to port the code to CircleCI 2.0
            PARAM_GO_VERSION="<< parameters.go-version >>"
            PARAM_GOPATH="<< parameters.gopath >>"

            GO_VERSION_FILE_PATH="${PARAM_GOPATH}/circleci/goversion"

            # set Go version
            GO_VERSION=${PARAM_GO_VERSION}
            if [ ! -z "${GO_VERSION}" ]; then
              echo "Go version specified as parameter is ${GO_VERSION}"
            elif [ -f ".palantir/go-version" ]; then
              GO_VERSION=$(cat ".palantir/go-version")
              echo "Go version specified in .palantir/go-version is ${GO_VERSION}"
            elif [ -f "/usr/local/go/VERSION" ]; then
              GO_VERSION=$(cat "/usr/local/go/VERSION")
              echo "Go version specified in /usr/local/go/VERSION is ${GO_VERSION}"
            else
              echo "Error: Go version was not specified as a parameter and neither .palantir/go-version nor /usr/local/go/VERSION exist"
              exit 1
            fi
            mkdir -p "$(dirname "${GO_VERSION_FILE_PATH}")"
            echo "Writing ${GO_VERSION} to ${GO_VERSION_FILE_PATH}"
            printf "%s" "$GO_VERSION" > "${GO_VERSION_FILE_PATH}"

  write-cache-key-file:
    description: |
      Preconditions:
        * File that contains the go version (for example, "go1.16.5") must exist at the path specified by the parameter
          "<< parameters.gopath >>/circleci/goversion"

      Writes a file at the location "<< parameters.gopath >>/circleci/circleci-cache-key-golang" that can be checksummed
      as part of a CircleCI cache key to save and restore a Go distribution. The cache key content depends on whether or
      not the required Go distribution is already present and the version of Go specified in the file at
      "<< parameters.gopath >>/circleci/circleci-cache-key-golang".
    parameters:
      <<: *gopath-param
    steps:
      - run:
          name: Writing cache key for golang distribution
          command: |
            # this pattern is used to make it easier to port the code to CircleCI 2.0
            PARAM_GOPATH="<< parameters.gopath >>"

            # set Go version
            GO_VERSION_FILE_PATH="${PARAM_GOPATH}/circleci/goversion"
            GO_VERSION="$(cat ${GO_VERSION_FILE_PATH})"
            echo "GO_VERSION=${GO_VERSION}"

            # write cache key. Content is based on whether or not required data is already present and the Go version.
            GO_CACHE_FILE_PATH="${PARAM_GOPATH}/circleci/circleci-cache-key-golang"
            mkdir -p "$(dirname ${GO_CACHE_FILE_PATH})"
            CACHE_KEY_FILE_CONTENT=""
            if [ -d "${PARAM_GOPATH}/go-dists/${GO_VERSION}" ]; then
              CACHE_KEY_FILE_CONTENT="Empty cache"
            else
              CACHE_KEY_FILE_CONTENT="${GO_VERSION}"
            fi
            echo "Writing cache key ${CACHE_KEY_FILE_CONTENT} to file ${GO_CACHE_FILE_PATH}"
            echo "${CACHE_KEY_FILE_CONTENT}" > "${GO_CACHE_FILE_PATH}"

  setup-cache:
    description: |
      Preconditions:
        * File that contains the go version (for example, "go1.16.5") must exist at the path specified by
          "<< parameters.gopath >>/circleci/goversion"
        * CircleCI cache restore step for Go distribution has already occurred

      Ensures that the Go distribution for the version specified in the file
      "<< parameters.gopath >>/circleci/goversion" exists at "<< parameters.gopath >>/go-dists/${GO_VERSION}". If a
      directory already exists at this location (for example, because it is part of the Docker base image), does
      nothing. Otherwise, if a directory exists at << parameters.gopath >>/circleci/go-dists/${GO_VERSION} (for example,
      because it was restored there by the CircleCI cache restore operation), it is moved to the expected location. If
      neither of those paths exist, the distribution is downloaded by appending the desired Go distribution to the
      provided "go-dist-download-url-prefix" parameter, is expanded into
      "<< parameters.gopath >>/circleci/go-dists/${GO_VERSION}" and then copied to
      "<< parameters.gopath >>/go-dists/${GO_VERSION}" (in this scenario, the directory is copied rather than moved so
      that the CircleCI cache save operation will save the directory in
      "<< parameters.gopath >>/circleci/go-dists/${GO_VERSION}").
    parameters:
      <<: *gopath-param
      go-dist-download-url-prefix:
        description: |
          Prefix of the download URL that should be used to download the Golang distribution. The prefix is joined with
          the desired Go distribution file (for example, "go1.16.5.linux-amd64.tar.gz").
        type: string
        default: "https://golang.org/dl/"
    steps:
      - run:
          name: Download go distribution and install standard libraries
          command: |
            # this pattern is used to make it easier to port the code to CircleCI 2.0
            PARAM_GOPATH="<< parameters.gopath >>"
            PARAM_GO_DIST_DOWNLOAD_URL_PREFIX="<< parameters.go-dist-download-url-prefix >>"

            # set Go version
            GO_VERSION="$(cat "${PARAM_GOPATH}/circleci/goversion")"
            GO_DIST_DIR="${PARAM_GOPATH}/go-dists/${GO_VERSION}"
            GO_DIST_CACHE_DIR="${PARAM_GOPATH}/circleci/go-dists/${GO_VERSION}"

            # desired distribution already exists: nothing to do
            if [ -d "${GO_DIST_DIR}" ]; then
              echo "${GO_DIST_DIR} exists: nothing to do"
              exit
            elif [ -d "${GO_DIST_CACHE_DIR}" ]; then
              # Desired distribution restored from cache: move to expected location
              echo "${GO_DIST_DIR} does not exist, but ${GO_DIST_CACHE_DIR} exists: move to expected location"
              mkdir -p "${PARAM_GOPATH}/go-dists"

              mv "${GO_DIST_CACHE_DIR}" "${GO_DIST_DIR}"
              exit
            fi

            # Desired distribution does not already exist and is not in cache: download and ensure that it exists in
            # location that will be cached and in expected location
            echo "Neither ${GO_DIST_DIR} nor ${GO_DIST_CACHE_DIR} exist"
            echo "Downloading golang distribution from ${PARAM_GO_DIST_DOWNLOAD_URL_PREFIX}${GO_VERSION}.linux-amd64.tar.gz..." && wget -q "${PARAM_GO_DIST_DOWNLOAD_URL_PREFIX}${GO_VERSION}.linux-amd64.tar.gz"
            echo "Expanding archive" && tar xf "${GO_VERSION}.linux-amd64.tar.gz"
            echo "Removing archive" && rm "${GO_VERSION}.linux-amd64.tar.gz"
            echo "Creating ${GO_DIST_CACHE_DIR}" && mkdir -p "${GO_DIST_CACHE_DIR}"
            echo "Moving expanded Go distribution to ${GO_DIST_CACHE_DIR}" && mv go "${GO_DIST_CACHE_DIR}"
            echo "Creating ${PARAM_GOPATH}/go-dists directory" && mkdir -p "${PARAM_GOPATH}/go-dists"
            echo "Copying expanded Go distribution to ${GO_DIST_DIR}" && cp -r "${GO_DIST_CACHE_DIR}" "${GO_DIST_DIR}"
            echo "Setting working directory to ${PARAM_GOPATH} to ensure that 'install std' command doesn't use local go.mod file" && cd "${PARAM_GOPATH}"
            echo "Running go install std for linux-amd64" && GOOS=linux GOARCH=amd64 "${GO_DIST_DIR}/bin/go" install std
            echo "Running go install std for linux-arm64" && GOOS=linux GOARCH=arm64 "${GO_DIST_DIR}/bin/go" install std
            echo "Running go install std for darwin-amd64" && GOOS=darwin GOARCH=amd64 "${GO_DIST_DIR}/bin/go" install std
            echo "Running go install std for darwin-arm64" && GOOS=darwin GOARCH=arm64 "${GO_DIST_DIR}/bin/go" install std
            echo "Running go install std for windows-amd64" && GOOS=windows GOARCH=amd64 "${GO_DIST_DIR}/bin/go" install std

  setup-symlink:
    description: |
      Preconditions:
        * File that contains the go version (for example, "go1.16.5") must exist at the path specified by the parameter
          "go-version-file-path"
        * Go distribution for the version must exist at "/go/go-dists/${GO_VERSION}"

      Sets up a symlink from /usr/local/go -> /go/go-dists/${GO_VERSION}
    parameters:
      <<: *gopath-param
    steps:
      - run:
          name: Set up symlink from /usr/local/go -> << parameters.gopath >>/go-dists/${GO_VERSION}
          command: |
            # this pattern is used to make it easier to port the code to CircleCI 2.0
            PARAM_GOPATH="<< parameters.gopath >>"

            # set Go version
            GO_VERSION_FILE_PATH="${PARAM_GOPATH}/circleci/goversion"
            GO_VERSION="$(cat ${GO_VERSION_FILE_PATH})"
            echo "GO_VERSION=${GO_VERSION}"

            if command -v sudo &> /dev/null; then
              sudo rm -rf /usr/local/go
              sudo ln -s /go/go-dists/${GO_VERSION} /usr/local/go
            else
              rm -rf /usr/local/go
              ln -s /go/go-dists/${GO_VERSION} /usr/local/go
            fi

  setup-go-distribution:
    description: |
      Sets up the Go distribution for a CircleCI job. If the distribution does not already exist in the expected
      location, it is retrieved and saved to the CircleCI cache.

      By default, uses the version of Go specified in the ".palantir/go-version" or the "/usr/local/go/VERSION" file.
      If a value is provided for the "go-version" parameter, then that version is used and no files are consulted. The
      Go version should be specified in the manner that matches how versions are declared in a Go distribution's VERSION
      file (for example, "go1.16.5").

      The "cache-key" parameter can be used to customize the cache key. Jobs that can run in parallel should specify
      unique "cache-key" values to ensure that there are no race conditions for cache save/restore opreations.
    parameters:
      <<: *gopath-param
      go-version:
        description: |
          If non-empty, this value is written as the Go version (files in the repository/image are not consulted). The
          version should be of the form specified in a Go distribution's VERSION file (for example, "go1.16.5").
        type: string
        default: ""
      cache-key:
        description: |
          String that is used as part of the cache key. Typically something like a job name.
        type: string
        default: ""
      go-dist-download-url-prefix:
        description: |
          Prefix of the download URL that should be used to download the Golang distribution. The prefix is joined with
          the desired Go distribution file (for example, "go1.16.5.linux-amd64.tar.gz").
        type: string
        default: "https://golang.org/dl/"
    steps:
      - write-go-version-file:
          go-version: << parameters.go-version >>
          gopath: << parameters.gopath >>
      - write-cache-key-file:
          gopath: << parameters.gopath >>
      - restore_cache:
          name: Restore Go distribution from cache
          keys:
            - &golang-cache-key v3-golang-<< parameters.cache-key >>-{{ checksum "<< parameters.gopath >>/circleci/circleci-cache-key-golang" }}
      - setup-cache:
          gopath: << parameters.gopath >>
          go-dist-download-url-prefix: << parameters.go-dist-download-url-prefix >>
      - setup-symlink:
          gopath: << parameters.gopath >>
      - run: go version
      - save_cache:
          name: Save Go distribution to cache
          key: *golang-cache-key
          paths:
            - << parameters.gopath >>/circleci/go-dists

jobs:
  verify:
    working_directory: /go/src/github.com/nmiyake/go-circle-orbs
    docker:
      - image: golang:1.16.5
    steps:
      - checkout
      - setup-go-distribution:
          cache-key: $CIRCLE_JOB
      - run: echo "Verify task"
  dist:
    working_directory: /go/src/github.com/nmiyake/go-circle-orbs
    docker:
      - image: golang:1.16.5
    steps:
      - checkout
      - setup-go-distribution:
          go-version: go1.15.11
          cache-key: $CIRCLE_JOB
      - run: echo "Dist task"
  ci-image:
    working_directory: /home/circleci/go/src/github.com/nmiyake/go-circle-orbs
    docker:
      - image: cimg/go:1.16-browsers
    steps:
      - checkout
      - setup-go-distribution:
          go-version: go1.15.11
          cache-key: $CIRCLE_JOB
          gopath: /home/circleci/go
      - run: echo "Dist task"

workflows:
  version: 2
  verify-dist-publish:
    jobs:
      - verify
      - dist
      - ci-image
