version: 2.1

orbs:
  go-dist: palantir/go-dist@0.0.1

jobs:
  verify:
    working_directory: /go/src/github.com/nmiyake/go-circle-orbs
    docker:
      - image: golang:1.16.5
    steps:
      - checkout
      - go-dist/setup-go-distribution:
          cache-key: "verify"
      - run: echo "Verify task"
  dist:
    working_directory: /go/src/github.com/nmiyake/go-circle-orbs
    docker:
      - image: golang:1.16.5
    steps:
      - checkout
      - go-dist/setup-go-distribution:
          cache-key: "dist"
          go-version: go1.15.11
      - run: echo "Dist task"
  publish:
    working_directory: /go/src/github.com/nmiyake/go-circle-orbs
    docker:
      - image: golang:1.16.5
    steps:
      - checkout
      - go-dist/setup-go-distribution:
          cache-key: "dist"
          go-version: go1.15.11
      - run: echo "Publish task"

workflows:
  version: 2
  verify-test-dist-publish:
    jobs:
      - verify
      - dist
      - publish:
          requires:
            - dist
